volumes:
  db-data:

services:
  db:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - db-data:/data
    restart: unless-stopped

  app:
    build: .
    environment:
      - REDIS_HOST=db
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_DEBUG=${APP_DEBUG}
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
